### ISSUE TITLE
Use static variables instead of functions for Vector2 class' direction methods.

### ISSUE THREAD

**Issue by TheDuckDev** [DucktapeEngine/Ducktape#10]
**What**
In the [Vector2.h header file](https://github.com/DucktapeEngine/Ducktape/blob/main/include/Ducktape/vector2.hpp), replace the static Vector2 Down, Left(), NegativeInfinity(), One(), PositiveInfinity(), Right(), Up(), Zero() methods with static variables that replace the methods.
**Why**
Seperate methods for this is unnecessary as all those methods do is return a specific Vector2() value. This can be done with just static variables.

**Comment by Qeolvdxu** [comment]
Hello @TheDuckDev, I am interested in this issue. Could you assign this issue to me?

**Comment by TheDuckDev** [comment]
@Qeolvdxu Done. :)

**Comment by TheDuckDev** [comment]
@Qeolvdxu Yup, it works now. But there still are errors (related to camera.cpp) and I can't merge this PR if the code doesn't compile properly. So I would appreciate if you could fix that as well. :)

**Comment by TheDuckDev** [comment]
I tried solving this issue myself, and it doesn't seem like it's possible. Using functions isn't a big deal, thus it's fine the way it is right now. But incase if anyone does think that it's possible, free feel to give it a go.

**Comment by Sable-20** [comment]
If the PR is closed this should be closed as well @TheDuckDev ;)

**Comment by TheDuckDev** [comment]
@Sable-20 The PR was closed but not merged. This issue was left open so if anyone wanted to give a go on fixing it, but yeah it's not that big of a deal so I'll close it now.
