### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by aryanbaburajan** [DucktapeEngine/Ducktape#104]
Write documentation for all the classes, methods, and members, that's all. :)
Here's a checklist for all the files:
**Engine:**
- [x] Component.h
- [x] MeshRenderer.h
- [x] DirectionalLight.h
- [x] PointLight.h
- [x] Tag.h
- [x] Transform.h
- [x] Configuration.h
- [x] Debug.h
- [x] Engine.h
- [ ] Entity.h
- [ ] LoopManager.h
- [ ] Macro.h
- [x] Scene.h
- [x] Time.h
- [x] Window.h
- [x] Input.h
- [x] Key.h
- [ ] Serialization.h
- [x] UserPointer.h
- [x] Camera.h
- [x] Cubemap.h
- [x] Mesh.h
- [ ] Renderer.h
- [x] Shader.h
- [x] Texture.h
- [x] Vertex.h

**Editor:**
- [ ] Editor.h
- [ ] EditorModules.h

**Comment by aryanbaburajan** [comment]
For Hacktoberfest contributors: Open a PR for every 5 or more files you document, for it to be properly merged.

**Comment by LordRibblesdale** [comment]
I would like to work on my first six: "Component.h", "MeshRenderer.h", "Tag.h", "Transform.h", "Configuration.h", "Debug.h". I cannot find "ModelExtractor.h"

**Comment by aryanbaburajan** [comment]
@LordRibblesdale Alright! Also ModelExtractor had been removed recently, but I forgot to update the issue; though I've updated it now.

**Comment by LordRibblesdale** [comment]
Whenever necessary, I'd like to continue in future days (I like to document code, professional deformation >.<), but I want to give others the possibility to make their PRs for Hacktoberfest ;)

**Comment by YeffyCodeGit** [comment]
Could I work on the `Time.h, Window.h, Scene,h, Color.h, Key.h and Engine.h` files?

**Comment by YeffyCodeGit** [comment]
By the way, I also wrote the docs for `Input.h`, as the key header doesn't really have much to document :D

**Comment by AshishKingdom** [comment]
Hello! I would like to work on `Shader.h`, `Vertex.h`, `Texture.h`, `Key.h`, `PointLight.h` and `DirectionalLight.h`
