### ISSUE TITLE
Add CI/CD

### ISSUE THREAD

**Issue by aryanbaburajan** [DucktapeEngine/Ducktape#106]
Create Github Actions to test compilation of Ducktape on every pull request. push, etc.

**Comment by HamzaRahmani** [comment]
I can work on this

**Comment by HamzaRahmani** [comment]
Would it be possible to get more details regarding the requirements?

**Comment by aryanbaburajan** [comment]
@HamzaRahmani Sure! There are no unit tests as of now, so no, just configure CMake and compile the source code in a Linux environment. Also you'd have to install the required packages from apt, before compilation, for the libraries to be linked.

**Comment by aryanbaburajan** [comment]
Fixed in #153.
