### ISSUE TITLE
Integrate Doxygen Awesome CSS with Doxygen

### ISSUE THREAD

**Issue by aryanbaburajan** [DucktapeEngine/Ducktape#131]
Integrate [doxygen awesome css](https://jothepro.github.io/doxygen-awesome-css/), with Doxygen to make modern style documentation rather than the outdated default style of Doxygen.

Configurations:
- Use the Sidebar-only theme
- Enable Dark Mode toggle

**Comment by AsmaKacem1** [comment]
Hey,Can you assign me this one?

**Comment by aryanbaburajan** [comment]
Someone else completed this due to inactivity of assigned user.

Also it looks really cool!
![image](https://user-images.githubusercontent.com/51789606/193760252-3d29899d-4f62-475e-a897-99a1114d7bc7.png)
