### ISSUE TITLE
Resource Browser

### ISSUE THREAD

**Issue by aryanbaburajan** [DucktapeEngine/Ducktape#133]
**Is your feature request related to a problem? Please describe.**
A File Explorer-like Window that could be used to navigate through the Resources (assets) used by the current project, with options to rename, and delete the files/directories.
It'd be great to also allow for searching for files based on their name, and for copying and pasting files between directories.

Similar to Unity's Asset window: 
![image](https://user-images.githubusercontent.com/51789606/193411663-abc33b7c-0100-4489-938a-80de1ad5b331.png)
Or Unreal's Asset Browser window:
![image](https://user-images.githubusercontent.com/51789606/193411682-703428e9-4eba-4411-8e2f-3b31e96700de.png)

**Comment by harrycarriers** [comment]
Im interested on working this.

**Comment by harrycarriers** [comment]
#158

**Comment by harrycarriers** [comment]
working on #159 its gonna be fixed soon I hope

**Comment by harrycarriers** [comment]
#162 passed all build tests.
