### ISSUE TITLE
wrong header extension

### ISSUE THREAD

**Issue by molor824** [DucktapeEngine/Ducktape#147]
**What**
Replace .h with .hpp or .hh
**Why**
Intellisense detecting it as C file

**Comment by aryanbaburajan** [comment]
As per [Reddit](https://www.reddit.com/r/cpp/comments/4vgjwm/why_h_is_more_widely_used_than_hpp_for_c_header/), `.h` is still the default extension used in most IDEs, so I'll have to pass on that.
