### ISSUE TITLE
Sprite stretches when Window size isn't in 1:1 ratio

### ISSUE THREAD

**Issue by TheDuckDev** [DucktapeEngine/Ducktape#2]
**Describe the bug**
The sprite appears stretched when the window's width and height are not in the ratio 1:1.

**To Reproduce**
1. Go to the file [./ducktape.h](https://github.com/DucktapeEngine/Ducktape/blob/main/ducktape.h).
2. Edit the `WIDTH` variable to something that's not the same as `HEIGHT` variable.
3. Build and run the program.

**Expected behavior**
The rendered sprite should appear in the same scale the original file is.

**Screenshots**
![image](https://user-images.githubusercontent.com/51789606/134795068-dfc058af-ab89-4115-8b73-3f22cce185b0.png)

**Comment by sgavil** [comment]
I would like to help here! :)

**Comment by TheDuckDev** [comment]
Tested it, works.
> This should be handled independently in a separate method in order to be able to correctly set the Viewport and calculate the new size to preserve the aspect ratio.

Do you mind explaining how one would do this? Perhaps by opening a new issue, thanks! :)
