### ISSUE TITLE
Add support for Windows, MacOS.

### ISSUE THREAD

**Issue by TheDuckDev** [DucktapeEngine/Ducktape#28]
I'm on Linux (Debian) and I can confirm that it works on Linux. I'd like a Windows-user and a MacOS-user to confirm that the code compiles + runs without any issues. 
According to [this SFML Forum](https://en.sfml-dev.org/forums/index.php?topic=19487.0):
> All the SFML code you write should compile without issues on all the supported platforms without modification.
> And if you stick to standard C++ and avoid any platform and compiler specific code then that should also be true for the rest of your application.

So if the code compiles, then it must mean that there is no need for a seperate Windows SFML version. Thus, we'd able to remove [this directory](https://github.com/DucktapeEngine/Ducktape/tree/main/include/SFML-windows-gcc).
Here's a task list for each platform:

- [ ] Windows
- [x] Linux
- [ ] MacOS

**Comment by RomKart** [comment]
is there a Windows build?

**Comment by TheDuckDev** [comment]
@RomKart After some testing I realized, windows/macos is not supported at the moment. I'll be working on this issue in the coming days.
