### ISSUE TITLE
GameObject::Instantiate()

### ISSUE THREAD

**Issue by TheDuckDev** [DucktapeEngine/Ducktape#32]
**Is your feature request related to a problem? Please describe.**
It'd be easier for the library-users to use a method to create new GameObject(s), rather than having to `push_back()` a `new GameObject()` to the `gameObjects` vector array. 

**Describe the solution you'd like**
An `GameObject::Instantiate()` static method that would append a new GameObject to the `gameObjects` array.

**Comment by Sable-20** [comment]
Duckie ill try and work on this

so ig add a in progress tag or assign me to it not sure if youve set that up
