### ISSUE TITLE
Integrate Box2D Physics system

### ISSUE THREAD

**Issue by TheDuckDev** [DucktapeEngine/Ducktape#4]
**Describe the solution you'd like**
A proper Physics system integrated into the game engine, similar to how it's done in other game engines like Unity.

**Additional context**
It would be implemented similar to how it's done in Unity:
There would be components for each type of colliders, and one for Rigidbody.

**Resources**
[Box2D](https://box2d.org/documentation/md__d_1__git_hub_box2d_docs_hello.html)

**Comment by luis-1063** [comment]
Hey @TheDuckDev, I am interested on working on this, Could you assign this to me?

**Comment by TheDuckDev** [comment]
@luis-1063 Done :)

**Comment by TheDuckDev** [comment]
I've finished this issue, although the physics engine isn't fully completed yet. It only supports box colliders right now, (rigidbodies with no colliders aren't supported either). I'll be making a new issue with a task list for the rest of the Physics Engine.
