### ISSUE TITLE
Docs

### ISSUE THREAD

**Issue by Sable-20** [DucktapeEngine/Ducktape#46]
you know what time it is

ill start by writing some docs in some MD files and maybe moving them to a wiki but we getting ready bois

**Comment by TheDuckDev** [comment]
@Sable-20 And where would the docs be hosted?

**Comment by Sable-20** [comment]
@TheDuckDev *in the docs folder and ill redo the entire website to include docs if I have to*

**Comment by Sable-20** [comment]
I'll start writing this in a bit I was having issues with the software I use to write docs

**Comment by TheDuckDev** [comment]
@Sable-20 Would you like me to start the documentation? I had started making one using [MkDocs](https://www.mkdocs.org/) and I haven't made much progress, but it's coming out nice.

**Comment by Sable-20** [comment]
I can definitely get the documentation I have sorted out the whole thing it was a small issue with my linux distro and I fixed it by downloading the sister software on windows

**Comment by Sable-20** [comment]
I do need access to the documentation repo though @TheDuckDev and then i can finish up

**Comment by TheDuckDev** [comment]
I realized it's unecessary to write documentations manually, while you can just auto generate them using doxygen.
So hip hop issue closed.
