### ISSUE TITLE
stop using raw pointers

### ISSUE THREAD

**Issue by molor824** [DucktapeEngine/Ducktape#48]
**Is your feature request related to a problem? Please describe.**
segfaults everywhere when people uses it (becase i suck at coding)

**Describe the solution you'd like**
use smart pointers

**Describe alternatives you've considered**
considered rust but he said no

**Additional context**
use std::vector, unique_trp, shader_ptr etc.

**Comment by TheDuckDev** [comment]
@molor824 Would you be willing to work on this issue?
