### ISSUE TITLE
Particle System

### ISSUE THREAD

**Issue by Z7RAGE** [DucktapeEngine/Ducktape#49]
**Is your feature request related to a problem? Please describe.**
There is no particle system that would let me create special visual effects.

**Describe the solution you'd like**
A flexible particle system component.

**Comment by TheDuckDev** [comment]
This issue has been turned into a feature and will be implemented soon.

**Comment by RomKart** [comment]
Yey! DuckTape's particle system :>

**Comment by roooof** [comment]
Hey @TheDuckDev I would like to work on this issue :D

**Comment by TheDuckDev** [comment]
This feature is not planned to be completed before the first Ducktape version, so it can't be worked on right now.

**Comment by Z7RAGE** [comment]
Who asked :trollface:

**Comment by Z7RAGE** [comment]
Leave my emails alone lol
