### ISSUE TITLE
In-built Sprite Editor Feature

### ISSUE THREAD

**Issue by RomKart** [DucktapeEngine/Ducktape#50]
Can I try making this?

[Edit]
This is a Pixel art editor inside the Game Engine, which makes users easy to use the engine!  So, we can make sprites easier and prolly faster! I guess we have some plans to make DuckTape for phones.. In those cases, this idea would be so helpful i guess! :)

**Comment by TheDuckDev** [comment]
@RomKart Please edit your original post and elaborate what the feature is about. Like how would the user edit their images through script. The Engine currently doesn't have a GUI editor and is only a library at the moment so it is not really a good idea crop/resize/etc. images through scripting.

**Comment by TheDuckDev** [comment]
@RomKart Yup that would be helpful. But as the game engine doesn't have an actual GUI Editor yet, how do you plan to let the users edit the sprites?

**Comment by RomKart** [comment]
Is Non-GUI Editor possible?

Like uhh.. a separate program for Ducktape Version1.0. till we get GUI Editor?

**Comment by TheDuckDev** [comment]
@RomKart That seems unecessary, and we will have to recreate this entire issue in Ducktape v2.0 when we actually do get a GUI Editor. Thus I'll be closing this issue for now.
