### ISSUE TITLE
Make Ducktape a library

### ISSUE THREAD

**Issue by TheDuckDev** [DucktapeEngine/Ducktape#53]
**What**

- [x] Proper file structure
- [x] Split .h files into .h and .cpp files so it can be compiled into binary
- [x] Make sure it compiles on Windows

**Why**
As of now, Ducktape can't really be called a library as, well, it's *not* a library. People can't even compile it on windows, neither can it be compiled into binary. So I made an issue to track all of the stuff that needs to be done.

More tasks to finish:
- [x] Link against all the binaries
- [x] Provide a `.so`, `.dll`, `.a`, and `.lib` binaries

**Comment by TheDuckDev** [comment]
I was thinking of not having task 2, and just split the files into source and header when the first release is being made. I really just hate working with two files so uh yeah.

**Comment by TheDuckDev** [comment]
Fixed.

**Comment by TheDuckDev** [comment]
Finished.

**Comment by Sable-20** [comment]
This needs to be re-opened, its still just an executable

in a few days I will switch the build system completely and itll build a library instead of an executable

You can assign me if you want as this is a quick fix with the right build system

**Comment by Sable-20** [comment]
For us to do to make it a library

- [ ] switch to meson since it has better support than cmake for linking against prebuilt binaries
- [ ]  link against all the binaries obviously
- [ ] provide a `.so`, `.dll`, `.a`, and `.lib`

**Comment by TheDuckDev** [comment]
Yep. Also why is there a need to switch to meson? CMake is one of the most commonly used build system so I'd say it's better to use that as most c++ users would already have that installed.
> You can assign me if you want as this is a quick fix with the right build system

Alright.

**Comment by TheDuckDev** [comment]
Actually, even better, how about we have all of the popular build systems? It'll be hard to manage but it'll be more convienient for users to build it. Build systems like Make, CMake, Premake, Ninjabuild.

**Comment by TheDuckDev** [comment]
I have made it so that it can build to .a files. Are the other formats necessary? Seems like there'd be some work to do. :sweat: 
Oh and, I haven't made it to build the examples, I wasn't sure how I should do it.
@Sable-20 Do you happen to have some idea on how? There's the flappybird.cpp file in the examples directory, and there'd be more examples, so we need a solution that lets us build all of the examples.

**Comment by Sable-20** [comment]
As I said when I contacted you elsewhere I can create GMake files and meson will provide us with VS build files, XCode build files, and Ninja build files. I can also hand make Premake files but CMake will be left up to you especially if you want to make a shared library.

**Comment by TheDuckDev** [comment]
It can compile examples now.
