### ISSUE TITLE
Fix Unit system

### ISSUE THREAD

**Issue by TheDuckDev** [DucktapeEngine/Ducktape#54]
**Describe the bug**
I'm having a lot of bugs dealing with units. In some place I need to use pixels as units, while in others, I don't.

**Comment by Sable-20** [comment]
try creating a universal unit that you can convert everything to and from. like `rem` in css will be converted too and from pixels based on screen size. take a look at mozilla docs for stuff like `rem` to get some ideas

**Comment by TheDuckDev** [comment]
There is a universal-unit-like-thingy that is 1u = 10px (u as in unit), which is being used in the `Camera::ScreenToWorldPos ()`and `Camera::WorldToScreenPos()` methods. I realized that *just* the camera doesn't use that unit system properly.

**Comment by Sable-20** [comment]
what seems to be the issue with the camera in particular? it shouldnt make a difference if you convert it back and forth properly

**Comment by TheDuckDev** [comment]
@Sable-20 Well that *is* the issue. My brain is running on like -100IQ so I'm sure I messed up the math somewhere.

**Comment by TheDuckDev** [comment]
Fixed
