### ISSUE TITLE
Fix GitHub Pages Website

### ISSUE THREAD

**Issue by asutoshvariar** [DucktapeEngine/Ducktape#69]
**Is your feature request related to a problem? Please describe.**
The active website is currently just a template.

**Describe the solution you'd like**
Use the built website instead of the Docusaurus README.

**Additional context**
<img width="1083" alt="Screen Shot 2022-01-12 at 8 35 13 AM" src="https://user-images.githubusercontent.com/96536388/149064458-09a1c862-b6de-4822-9d8b-b7d39cc07055.png">

**Comment by lines-of-codes** [comment]
Hello, I understand this problem and so, The problem was that the site hasn't been built. So yes, The setup of the site hasn't been finished.
