### ISSUE TITLE
Switch to ECS

### ISSUE THREAD

**Issue by TheDuckDev** [DucktapeEngine/Ducktape#72]
meh people said unity like paradigm sucks so im gonna do a tiny little switch
perhaps by using the EnTT library

**Comment by Sable-20** [comment]
Unity uses ECS now iirc ;-;

**Comment by lines-of-codes** [comment]
Unity still uses the same Game object-Component system (if I'm not wrong)
Though there's a package for you to be able to use the ECS system. Though currently it's well... not finished and currently does not support either URP or HDRP.

**Comment by AurumByte** [comment]
It’s fine to use an ECS paradigm, as long as it doesn’t clutter up a user’s code 😁

**Comment by TheDuckDev** [comment]
I decided that Ducktape should be a beginner friendly engine thus it'll not be integrating ECS.
