### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by TheSlayerishere** [DucktapeEngine/Ducktape#73]
**What**
Add comments explaining the source code 
as for where, pretty much all of the ducktape, and you know it
**Why**
It'll be a pain if we forget how the entire thing works, besides, it is handy to be able to get information from comments rather than visiting the documentation every single time for every single thing.

Besides, it'll help with IDE hinting, which will make the process of using ducktape a lot easier for most people.

**Comment by TheDuckDev** [comment]
Working on it as part of the documentation 👍

**Comment by TheDuckDev** [comment]
FInished 👍
