### ISSUE TITLE
Grammer error

### ISSUE THREAD

**Issue by Z7RAGE** [DucktapeEngine/Ducktape#76]
**What**
In Ducktape's Description "Lightweight" has a space which is not grammerly correct
**Why**
I just want github contributions lol

**Comment by TheDuckDev** [comment]
Fixed.
Also — Feel free to contribute to the engine properly, we highly appreciate contributions. But do note that as we're this :pinching_hand: close to our first release and there aren't many issues left, there aren't many things to contribute to. But we will be sure to flood the issue list once the engine gets released! :D
