### ISSUE TITLE
Change build scripts from Batch to Powershell.

### ISSUE THREAD

**Issue by YeffyCodeGit** [DucktapeEngine/Ducktape#77]
**Is your feature request related to a problem? Please describe.**
Ducktape currently has both .sh and .bat scripts, so the scripts work on all platforms. Switching to using Powershell will simplify this, because with one script you can support all platforms, as Powershell is cross-platform.

**Describe the solution you'd like**
Remove batch and shell scripts and make them Powershell scripts.

**Comment by TheDuckDev** [comment]
👍
